# Generated by Django 4.2.4 on 2023-10-04 16:54

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0003_rename_address1_shippingaddress_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="shippingaddress",
            name="phone",
            field=phone_field.models.PhoneField(
                blank=True, help_text="Введіть свій номер телефону", max_length=31
            ),
        ),
    ]
