# Generated by Django 4.2.4 on 2023-10-19 15:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0005_alter_shippingaddress_phone_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shippingaddress",
            name="address",
        ),
        migrations.AddField(
            model_name="shippingaddress",
            name="warehouse_number",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="shippingaddress",
            name="state",
            field=models.CharField(max_length=300),
        ),
    ]
