# Generated by Django 4.2.4 on 2023-10-01 14:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0002_product_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="stock",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
