# Generated by Django 4.2.4 on 2023-10-02 12:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0003_product_stock"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
