# Generated by Django 4.2.4 on 2023-10-04 15:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0005_alter_product_description_alter_product_slug_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(max_length=255),
        ),
        migrations.AlterField(
            model_name="product",
            name="title",
            field=models.CharField(max_length=250),
        ),
    ]
